### ISSUE TITLE
Fix docker hub description upload

### ISSUE THREAD

**Issue by mriedmann** [humhub/docker#2]
As stated [here](https://github.com/peter-evans/dockerhub-description) personal access tokens (PAT) can not be used to update the repository description at docker-hub. Having a proper readme without the overhead of maintaining 2 copies is almost mandatory for this project.

2 Options:
1. Add the "real" password into the secret. If we use this account only to handle the public humhub image repository it should be fine. We can fix this when docker-hub enables support of PAT with this API.
2. Enable Autobuild (by adding a service-account to docker-hub)

**Comment by mriedmann** [comment]
@luke- Any news on this front :smile:

**Comment by luke-** [comment]
@mriedmann Ups, somehow the answer got lost here - of course I added the secrets immediately :-)

![image](https://user-images.githubusercontent.com/4736168/92894457-e6feb280-f41a-11ea-8615-55e3ad5606fc.png)

Is that okay?

**Comment by mriedmann** [comment]
hm ok ... so you already added the cleartext password to the secret (not the personal access token)? If we have another problem that I cannot explain (https://github.com/humhub/docker/runs/1102292358?check_suite_focus=true). The interesting part is, that we can upload the image but cannot change the description.

**Comment by luke-** [comment]
I did this: `To store the credential (username + token) we should create 2 secrets (DOCKER_USERNAME, DOCKER_PASSWORD) on repository or even organizational level in github (Organization > Settings > Secrets > .`

Hmm thats strange @description

**Comment by mriedmann** [comment]
> As stated here personal access tokens (PAT) can not be used to update the repository description at docker-hub. Having a proper readme without the overhead of maintaining 2 copies is almost mandatory for this project.

~~If we want an up-to-date description we have to use the actual password instead of the token. An alternative would be using a GitHub service account and then enable the auto-build-feature on docker-hub.~~

I will find a better way around that. It might be a good idea to prepare this image to be part of the "official" docker library. Until then I will find another way around that issue. Closing this for now.
